[workspace]

members = [
  "staking_rewards",
  "staking_rewards_tests",
  "erc20",
  "staking_rewards_crate",
  "erc20_crate",
  "test_contract",
  "reentrancy_guard_crate",
  "rewards_distribution_recipient_crate"
]

[profile.release]
codegen-units = 1
lto = true
